### ISSUE TITLE
Unable to print anything on the LCD-Display

### ISSUE THREAD

**Issue by Silipwn** [fdebrabander/Arduino-LiquidCrystal-I2C-library#20]
I'm using a 16*2 LCD Display, with an Arduino Uno R3, but am unable to display anything on the LCD, I can toggle the backlight though.

**Comment by ibacktocode** [comment]
I have the same issue

**Comment by Silipwn** [comment]
@ibacktocode Any other library that worked out?

**Comment by Silipwn** [comment]
Try using this [library](https://bitbucket.org/fmalpartida/new-liquidcrystal/wiki/Home)
