### ISSUE TITLE
where i can connect my pins 

### ISSUE THREAD

**Issue by salmanfarisvp** [fdebrabander/Arduino-LiquidCrystal-I2C-library#7]
am trying the helloworld example and i don't know where i can connect the SCL and SDA pin's 
and how to find I2C address  fro arduino uno

**Comment by anas1091** [comment]
hello
sda to pin 4
scl to pin 5

**Comment by MikeS2058** [comment]
On the Nano I am using, the pins are A4 and A5.

**Comment by salmanfarisvp** [comment]
Thanks @anas1091  and @MikeS2058  .
I used Arduino I2C Scanner in order to get the I2C device address (https://github.com/salmanfarisvp/Arduino-Sensor/tree/master/LiquidCrystal_I2C/examples/I2C_Address%20Scanner) .

 and i used https://github.com/salmanfarisvp/Arduino-Sensor/tree/master/LiquidCrystal_I2C libraray .
